language: go
go_import_path: github.com/coreos/alb-ingress-controller
sudo: required

env:
  global:
    - HELM_VERSION=v2.5.0

go:
  - 1.8

services:
  - docker

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - curl -L https://kubernetes-helm.storage.googleapis.com/helm-$HELM_VERSION-linux-amd64.tar.gz | tar -xz -C /tmp
  - mv /tmp/linux-amd64/helm /tmp
  - /tmp/helm init -c

notifications:
  on_success: never
  on_failure: never

script:
  - ./test.sh
  - make server

after_success:
  - export COMMIT=`echo $TRAVIS_COMMIT | head -c 7`
  - docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io
  - export REPO=quay.io/coreos/alb-ingress-controller
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build --pull -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker push $REPO
  - /tmp/helm lint --strict alb-ingress-controller-helm/
  - if [ "$TRAVIS_BRANCH" = "master" ]; then ./helm_push.sh; fi
