site_name: AWS LoadBalancer Controller
repo_name: kubernetes-sigs/aws-alb-ingress-controller
repo_url: https://github.com/kubernetes-sigs/aws-alb-ingress-controller
strict: true

nav:
  - Home: README.md
  - Guide:
      - Controller:
          - Installation: guide/controller/installation.md
          - Configurations: guide/controller/configurations.md
          - Subnet Discovery: guide/controller/subnet_discovery.md
          - Pod Readiness Gate: guide/controller/pod_readiness_gate.md
      - Ingress:
          - Annotations: guide/ingress/annotations.md
          - Spec: guide/ingress/spec.md
          - Certificate Discovery: guide/ingress/cert_discovery.md
      - Service:
          - NLB-IP mode: guide/service/nlb_ip_mode.md
          - Annotations: guide/service/annotations.md
      - TargetGroupBinding:
          - TargetGroupBinding: guide/targetgroupbinding/targetgroupbinding.md
          - Spec: guide/targetgroupbinding/spec.md
      - Tasks:
          - Cognito Authentication: guide/tasks/cognito_authentication.md
          - SSL Redirect: guide/tasks/ssl_redirect.md
      - Walkthrough:
          - EchoServer: guide/walkthrough/echo_server.md
      - Upgrade:
          - Migrate v1 to v2: guide/upgrade/migrate_v1_v2.md
plugins:
  - search
theme:
  name: material
  language: en
  favicon: assets/images/aws_load_balancer_icon.svg
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - tabs
  custom_dir: docs/theme_overrides
# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true
extra_css:
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
extra_javascript:
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js