apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - kustomizeconfig.yaml

resources:
  - manifests.yaml
  - service.yaml

patches:
  - path: pod_mutator_patch.yaml
  - path: service_mutator_patch.yaml
  - path: ingressclassparams_validator_patch.yaml
  - path: globalaccelerator_validator_patch.yaml
