apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    {{- include "aws-load-balancer-controller.labels" . | nindent 4 }}
  name: {{ include "aws-load-balancer-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  egress:
  - {}
  ingress:
  - ports:
      - port: {{ .Values.webhookBindPort | default 9443 }}
        protocol: TCP
      - port: {{ (split ":" .Values.metricsBindAddr)._1 | default 8080 }}
        protocol: TCP
  podSelector:
    matchLabels:
      {{- include "aws-load-balancer-controller.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
  - Ingress
