apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: default-backend
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "defaultBackend.fullname" . }}
spec:
  replicas: {{ .Values.defaultBackend.replicaCount }}
  template:
    metadata:
    {{- if .Values.defaultBackend.podAnnotations }}
      annotations:
{{ toYaml .Values.defaultBackend.podAnnotations | indent 8}}
    {{- end }}
      labels:
        app: {{ template "name" . }}
        component: default-backend
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "name" . }}-default-backend
          image: "{{ .Values.defaultBackend.image.repository }}:{{ .Values.defaultBackend.image.tag }}"
          imagePullPolicy: "{{ .Values.defaultBackend.image.pullPolicy }}"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
              protocol: TCP
        {{- if .Values.defaultBackend.resources }}
          resources:
{{ toYaml .Values.defaultBackend.resources | indent 12 }}
        {{- end }}
    {{- if .Values.defaultBackend.image.pullSecretName }}
      imagePullSecrets:
        - name: "{{ .Values.defaultBackend.image.pullSecretName }}"
    {{- end }}
    {{- if .Values.defaultBackend.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.defaultBackend.nodeSelector | indent 8 }}
    {{- end }}
      terminationGracePeriodSeconds: 60

