apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: controller
resources:
- controller.yaml
patches:
- path: iam_for_sa_patch.yaml
- path: security_context_patch.yaml
images:
- name: controller
  newName: public.ecr.aws/eks/aws-load-balancer-controller
  newTag: v2.16.0
