name: Unit Test
on:
  - push
  - pull_request
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go Version
      run: echo "GO_VERSION=$(cat .go-version)" >> $GITHUB_ENV
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run unit tests
      run: |
        sudo snap install yq
        make test

    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./cover.out # optional

  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: make quick-ci
        run: |
          make quick-ci
